language: csharp
solution: csharp-csv-reader.sln

jobs:
  include:
    - dotnet: 6.0.100
      mono: none
      script:
        - dotnet restore ./src/net50/src.net50.csproj
        - dotnet build ./src/net50/src.net50.csproj
        - dotnet test ./tests/net50/tests.net50.csproj
    - dotnet: 2.1.502
      mono: none
      script:
        - dotnet restore ./src/netstandard20/src.netstandard20.csproj
        - dotnet build ./src/netstandard20/src.netstandard20.csproj
        - dotnet test ./tests/netstandard20/tests.netstandard20.csproj
      