language: csharp
mono: latest
solution: csharp-csv-reader.sln
install:
  - nuget restore csharp-csv-reader.sln
  - nuget install NUnit.ConsoleRunner -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release csharp-csv-reader.sln  
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/net20/bin/Release/tests.net20.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/net40/bin/Release/tests.net40.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/net45/bin/Release/tests.net45.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/net45/bin/Release/tests.net50.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./tests/netstandard20/bin/Release/tests.netstandard20.dll
