language: csharp
solution: csharp-csv-reader.sln

jobs:
  include:
    - dotnet: 6.0.100
      mono: none
      script:
        - dotnet restore ./src/net60/src.net60.csproj
        - dotnet build ./src/net60/src.net60.csproj
        - dotnet test ./tests/net60/tests.net60.csproj
    - dotnet: 5.0.201
      mono: none
      script:
        - dotnet restore ./src/net50/src.net50.csproj
        - dotnet build ./src/net50/src.net50.csproj
        - dotnet test ./tests/net50/tests.net50.csproj
    - dotnet: 2.1.502
      mono: none
      script:
        - dotnet restore ./src/netstandard20/src.netstandard20.csproj
        - dotnet build ./src/netstandard20/src.netstandard20.csproj
        - dotnet test ./tests/netstandard20/tests.netstandard20.csproj
    - script:
        - nuget restore ./src/net20/src.net20.csproj
        - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
        - msbuild /p:Configuration=Debug ./tests/net20/tests.net20.csproj
        - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./tests/net20/bin/Debug/tests.net20.dll