language: csharp
dotnet: latest
mono: latest
solution: csharp-csv-reader.sln
install:
  - nuget restore csharp-csv-reader.sln
  - nuget install NUnit.Console -Version 3.4.0 -OutputDirectory testrunner
script:
  - dotnet build csharp-csv-reader.sln
  - xbuild src/net20/src.net20.csproj
  - xbuild src/net40/src.net40.csproj
  - dotnet build src/netstandard20/src.netstandard20.csproj
  - xbuild tests/net20/tests.net20.csproj
  - xbuild tests/net40/tests.net40.csproj
  - dotnet build tests/netstandard20/tests.netstandard20.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe ./tests/net20/bin/Debug/tests.net20.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe ./tests/net40/bin/Debug/tests.net40.dll
  - dotnet test /tests/netstandard20/tests.netstandard20.csproj
after_success:
  - echo "Branch is $TRAVIS_BRANCH"
  - echo "Pull Request is $TRAVIS_PULL_REQUEST_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "I would publish to nuget here"; fi
