language: csharp
solution: csharp-csv-reader.sln

jobs:
  include:
    - dotnet: 6.0.100
      mono: none
      script:
        - dotnet restore
        - dotnet test
    - dotnet: 5.0.201
      mono: none
      script:
        - dotnet restore
        - dotnet test
