language: csharp
solution: csharp-csv-reader.sln
install:
  - nuget restore csharp-csv-reader.sln
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug csharp-csv-reader.sln
  - mono ./testrunner/NUnit.Runners.3.6.0/tools/nunit-console.exe ./tests/bin/Debug/CSVTestSuite.net20.dll
  - mono ./testrunner/NUnit.Runners.3.6.0/tools/nunit-console.exe ./tests/bin/Debug/CSVTestSuite.net35.dll
  - mono ./testrunner/NUnit.Runners.3.6.0/tools/nunit-console.exe ./tests/bin/Debug/CSVTestSuite.net40.dll
	  