name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore (NetStandard2.0)
      run: dotnet restore ./src/netstandard20/src.netstandard20.csproj
    - name: Build (NetStandard2.0)
      run: dotnet build ./src/netstandard20/src.netstandard20.csproj
    - name: Test (NetStandard2.0)
      run: dotnet test ./tests/netstandard20/tests.netstandard20.csproj
